# 커밋 주의 파일

#kakao:
#  springboot_blog_project:
#    REST_API_KEY: ec9cccfc0ee9d04942e1e8d3751201d7 # 빈칸으로 커밋, 앱 구동시 https://developers.kakao.com/console/app/844803 에서 복사붙여넣기
#    REDIRECT_URI: http://localhost:8080/auth/kakao/callback # 빈칸으로 커밋, 앱 구동시 https://developers.kakao.com/console/app/844803/product/login 에서 복사붙여넣기
#    ADMIN_KEY:  b539bd1073ca00c930411ee521da9961 # 빈칸으로 커밋, https://developers.kakao.com/console/app/844803  에서 복사붙여넣기
#    PUBLIC_PASSWORD :  test123 # 원래는 빈칸으로 커밋, 정해놓은 특정 값 사용.  TODO: 실제 운영시에도 이런 값으로 oAuth 패스워드를 사용하는지 확인 필요

# OAuth2 Client 라이브러리 key
spring:
  #참고 - https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 입력해주세요
            client-secret: 입력해주세요
            scope:
              - email
              - profile

#facebook은 잘 사용 안하는 거라 주석처리함
          # "https://developers.facebook.com/docs/facebook-login/web#--------"에서 facebook scope 확인
#          facebook:
#            client-id: 입력해주세요
#            client-secret: 입력해주세요
#            scope:
#              - email
#              - public_profile

          # 네이버는 OAuth2.0 공식 지원대상이 아니라서 client-name, authorization-grant-type, redirect-uri, provider 설정이 필요하다.
          # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.
          naver:
            client-id: 입력해주세요
            client-secret: 입력해주세요
            scope:
              - name
              - email
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code # 인증 방식은 뭘 사용하는지.
            redirect-uri: 입력해주세요

          kakao:
            client-id: 입력해주세요
            client-secret: 입력해주세요
            scope:  # 사용자에게 동의 요청할 동의 항목 ID 목록
              - account_email
              - profile_nickname
              - gender
            client-name: KaKao # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code # 인증 방식은 뭘 사용하는지.
            redirect-uri: 입력해주세요
            client-authentication-method: POST

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 인증 요청
            token-uri: https://nid.naver.com/oauth2.0/token # 접근 토큰 발급 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 접근 토큰을 이용하여 프로필 API 호출하기 - 프로필 정보 조회
            user-name-attribute: response # 네이버가 회원정보를 json 데이터인 response라는 키값으로 리턴해줌.

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 로그인 인증 요청
            token-uri: https://kauth.kakao.com/oauth/token # 접근 토큰 발급 요청
            user-info-uri: https://kapi.kakao.com/v2/user/me # 접근 토큰을 이용하여 프로필 API 호출하기 - 프로필 정보 조회
            user-name-attribute: kakao_account # 카카오가 회원정보를 json 데이터인 response라는 키값으로 리턴해줌.